/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-secondary-container": "#247155",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#dec29a",
        "surface-variant": "#d3e4fe",
        "tertiary-container": "#271901",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#213145",
        "secondary-fixed-dim": "#8bd6b4",
        "primary-fixed-dim": "#bec6e0",
        "primary-fixed": "#dae2fd",
        "surface-container-high": "#dce9ff",
        "secondary-container": "#a6f2cf",
        "on-tertiary-fixed": "#271901",
        "on-surface": "#0b1c30",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed": "#131b2e",
        "error": "#ba1a1a",
        "surface-container": "#e5eeff",
        "primary": "#000000",
        "on-primary-container": "#7c839b",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-container": "#98805d",
        "background": "#f8f9ff",
        "inverse-primary": "#bec6e0",
        "outline-variant": "#c6c6cd",
        "outline": "#76777d",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed-variant": "#00513a",
        "primary-container": "#131b2e",
        "tertiary": "#000000",
        "secondary-fixed": "#a6f2cf",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "on-background": "#0b1c30",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002115",
        "surface-tint": "#565e74",
        "inverse-on-surface": "#eaf1ff",
        "secondary": "#1b6b4f",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#45464d",
        "tertiary-fixed": "#fcdeb5",
        "on-tertiary-fixed-variant": "#574425"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "6px",
        "xl": "72px",
        "xs": "6px",
        "gutter": "24px",
        "margin": "48px",
        "md": "24px",
        "sm": "12px",
        "lg": "48px"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "display-hero": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"]
      },
    },
  },
  plugins: [],
}
